---

- name: restart
  service:
    name: "{{ _name_ }}"
    state: restarted
  when: (ansible_distribution_major_version == '6' and whoami_output.stdout == 'root')

- name: restart
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ _name_ }}"
  when: (ansible_distribution_major_version == '7' and whoami_output.stdout == 'root')


