monit_services:
  - name: sshd
    type: process
    target: /var/run/sshd.pid
    start: /usr/sbin/service sshd start
    stop: /usr/sbin/service sshd stop
  - name: apache
    type: process
    target: /var/run/apache2.pid
    start: /usr/sbin/service apache2 start
    stop: /usr/sbin/service apache2 stop
    restart: /usr/sbin/service apache2 restart
    rules:
      - "if failed port 80 protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"
  - name: my_file
    type: file
    target: /etc/monit/monitrc
    rules:
      - "if changed timestamp then exec \"/bin/bash -c 'echo `data` >> /tmp/foo.bar.changed'\""
  - name: my_filesystem
    type: filesystem
    target: /dev/sda1
    rules:
      - "if space usage > 80% for 5 times within 15 cycles then alert"
  - name: my_directory
    type: directory
    target: /etc/monit
    rules:
      - "if timestamp < 1 hour then alert"
  - name: google
    type: host
    target: google.com
    rules:
      - "if failed port 443 type tcpSSL protocol http then alert"
  - name: localhost
    type: system
    rules:
      - "if loadavg (1min) > 2 then alert"
      - "if loadavg (5min) > 2 then alert"
      - "if memory usage > 75% then alert"
      - "if cpu usage (user) > 70% for 8 cycles then alert"
      - "if cpu usage (system) > 40% for 8 cycles then alert"
      - "if cpu usage (wait) > 20%  for 8 cycles then alert"
